### ISSUE TITLE
Identifiers taking a long time due to using crypto/rand

### ISSUE THREAD

**Issue by gwd** [wcharczuk/go-incr#19]
First, thank so SO MUCH for this amazing package.  I didn't know it but incremental computation is something I've been wanting for a year or two for one of my projects, and your package has saved me a lot of effort and false starts.

One thing I noticed when doing testing, was that a significant amount of time in my testing was spent in `rand.Read()` when creating new identifiers: for the basic test with 200 input units (which results in probably 1-2k nodes), setting up the graph takes nearly 2 seconds.  Since the prototype "real" system has 8000 units, and I'm hoping to scale that into tens of thousands, that will be a significant issue.

I've done simple tests just replacing `crypto/rand` with `math/rand`, an the problem goes away.  Since I don't expect this to be a security-sensitive domain, I'd like at least the option of switching to math/rand.  (And you might consider defaulting to math/rand, and allowing people to opt into crypto/rand if they need the extra security.)

I'm happy to send you a PR, but I wanted to get your input on the best way to solve the issue.  I guess you'd want to pass that as an option to NewGraph(); but the problem is NewIdentifier() is called all over the place in contexts where graph isn't available.  So unless you ether just switch unilaterally to `math/rand`, or have a global variable for the rand source, it will require a lot of refactoring.

Let me know if you have any ideas.

**Comment by wcharczuk** [comment]
Hey @gwd congrats on the first issue on this repo!

Yeah the choice of `crypto/rand` versus `math/rand` for identifier setup was motivated by google's choice for `crypo/rand` in their library for v4 uuids (https://github.com/google/uuid/blob/master/uuid.go#L9).

I think a narrow fix here is to use their pooled approach for spinning up identifiers to help with throughput. I'll take a crack at that tonight.

**Comment by wcharczuk** [comment]
I had a free second right now, if you pull latest `main` it should have the new version of the identifier generator (using the pooled approach similar to google's). In local benchmarking it performed about as well as `math/rand` (i.e. a 2x speedup) but let me know if it does the same for you.

**Comment by wcharczuk** [comment]
Specifically going forward, if `math/rand` is still significantly faster, I can add a top level setting function (e.g. `UseInsecureRandomForIdentifiers(bool)` to configure which random reader to use.

I'm hesitant to default to `math/rand` given `crypto/rand` is the existing behavior, but it would be an easy way to switch out for folks that do want the extra performance.

**Comment by gwd** [comment]
Hey!  Benchmarking a hotspot does seem to be the same between using math/rand and your new pool method.  Thanks for the quick response!

**Comment by wcharczuk** [comment]
A couple bits of context
- Profiling in go is a snapshot profiler, that is, every Q quantum a stack dump is taken of all the goroutines, their frames are aggregated (moving left to right basically is start to finish over the profiling period, but not really).
- As a result, the "width" of a flamegraph segment can be thought of as "the relative amount of time a random stack trace has this function in it" which can mean one of two things; your code is spending a lot of time in that function because it takes a long time to execute, _or that function is called very frequently_.

Based on my testing, and unless something is very esoteric about your setup, there are not meaningful gains in switching to `math/rand` at this point. I went even so far as to test what would happen if you just binary encoded an atomically incremented uint64 as a [16]byte for the identifier, and it was basically the same as the pooled crypto rand read and the `math/rand` read. Further, `math/rand`.Read is marked as deprecated, and I would rather not have that lint warning + exception if possible.

All this to say, I think the identifier code is about as fast it can be.

The only other thing that jumps out from your flamegraphs (which are super helpful, btw!) is that in one you're using `Map` and the other you're using `MapN`; is that intentional? That might have some performance implications, but also likely not.

Finally, the library generally isn't super optimized for creating graphs, there is a lot of consideration given to computing the heights correctly on start, and deferring as little work as possible so that `Stabilize` calls are fast. This extends from the library generally being used in an "online" capacity where you eat the cost of instantiating ~8k nodes (1) time and then push a lot of updates through the graph with `Stabilize` over the lifetime of the program. 

One last thing to zoom in on; how are you observing the graph? Is the entire graph required? Do you wait until the graph is mostly constructed before adding observers? This may help a bit in reducing the churn (a lot of work is done when you observe nodes, as that marks them as necessary and then the entire tree up from there).

**Comment by gwd** [comment]
So to give you some context: This incremental computation is replacing a SQL query that's about 7 layers deep.  The total computation has 3 "global" variables, then each "readunit" has 6 internal variables and 4 observation varibles, and each "word" has 9 internal variables and 6 observation variables; since a word may be in multiple readunits and each readunit has multiple words, you get quite a "web" of connections by the end.   So yes, some of the variables are maps of a fixed number of inputs, usually of different types (using `Map`); and some have an indeterminate number of inputs of the same  type (`MapN`).  The observation variables are basically necessary; the end computation will choose a specific "readunit" to study, but it's helpful for the end user to understand why a given readunit was chosen (i.e., because of the properties of this specific word -- hence the internal observation variables).

The vast majority of operations are incremental; and even with a "naive" implementation, it's already 4x faster than the SQL version.  I'm sure that could be made tens of times faster still by the judicious use of `Cutoff()`.  So I definitely appreciate the work you've put in to make Stabilize fast.

But the performance of "opening" the connection is still something to think about, and there are a number of operations where it's awkward to modify the computation in-place: If, for instance, the mapping of readunit to words change, then excising the connections from `MapN` variables is a lot more work than just recomputing the whole tree.

One thing that's almost certainly an inefficiency in the current set-up function is that it will call Add() repeatedly for a MapN variable, even when a full slice's worth is known.  I actually only noticed yesterday that you can pre-populate MapN variables; that should git rid of the vast majority of `growslice` operations.  If adding observers as then last step would be more efficient, I could look at rearranging that as well.

Regarding samples: I understand in general how the samples work; but what I'm not sure of is, in the flame graph, how they interact with goroutines executing in parallel.  It looks like the time reported on the flame graph is wall-clock time; but of course the runtime does lots of work in background goroutines.  Having the `growslice` and other such work done by background goroutines would be one explanation of why slashing go-incr.NewIdentifier() would result in only a small improvement in wall-clock-time.

At any rate, let me do the optimizations I know I can do -- adding observers at the end, and adding contents of MapN() variables at creation when possible rather than repeatedly calling Add().  Then I'll try it again with idpool vs mathrand and see what results we get.

Thanks as always for your time, and the library!

**Comment by gwd** [comment]
Hey,  just a quick follow-up -- here's the results from adding all the observations at the end (using `math/rand` rather than your "idpool" solution), after all the internal nodes had been set up.  (`func5` and `func2` are the functions which initialize the observation nodes at the very end.)  It shifted the work around, but it doesn't look like it fundamentally made anything faster.  NB the performance here isn't a critical thing for me (at least not yet), but if it does become an issue, I might take a look at whether any of the node creation stuff could be made more efficient by pre-allocating, as growing maps and slices seems to be a fairly significant amount of the work being done.

So  with that, I think I'm done for now (unless you're particularly motivated to dig into the performance of MustObserve(), in which case I'm happy to run some more benchmark / profile runs).

Thanks again!

<img width="1583" alt="Screenshot 2024-04-10 at 12 04 41 PM" src="https://github.com/wcharczuk/go-incr/assets/1247773/b10f4a6d-13db-4971-a5a1-0dfc1f3cfc7f">

**Comment by wcharczuk** [comment]
👋 One more optimization worth trying; I've added some new options for the graph itself (specifically `OptGraphPreallocateNodesSize(size)`) that will let you set the initial capacity of the backing node map to cut down on some overhead in bootstrapping large graphs. There are separate options for `Observers` and `Sentinels` as well if you have large numbers of those.

The performance impact looks somewhat decent:

<img width="913" alt="Screenshot 2024-04-10 at 12 05 11 PM" src="https://github.com/wcharczuk/go-incr/assets/697472/941f4e76-fd19-4f46-9bd7-c402cd33e9d3">

Hopefully this helps!

**Comment by wcharczuk** [comment]
I've added a new top level function `SetIdentifierProvider` which will let you add a custom implementation of the `NewIdentifier` function. I've also added a basic implementation of an atomic counter based provider as an example. The existing providers aren't exported for now, so this will be very much an "experts only" method.

**Comment by gwd** [comment]
Great, thanks for all your help.
